import Head from "next/head";
import Image from "next/image";
import AboutMe from "../components/AboutMe/AboutMe";
import BlogListing from "../components/BlogListing/BlogListing";
import ContactMe from "../components/ContactMe/ContactMe";
import Container from "../components/container/container";
import NavBar from "../components/NavBar/NavBar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Brandon Holz - Full stack developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <BlogListing />
      <AboutMe />
      <hr className="pb-32" />
      <ContactMe />
    </div>
  );
}
